name: Workflow Dispatch Free Form Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is a description for the created environments
        required: true

      test-suite:
        description: Select the Required Test Suite to run
        type: environment





      Tags:
        description: This a True or false Tag
        type: boolean
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "We did the Thing to ${{ github.event.inputs.environment }} Env and The Test ${{ github.event.inputs.test-suite }}"

  Notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo " Add The ${{ github.event.inputs.Tags }}"

